# Generated by Django 3.2.3 on 2021-06-02 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210531_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Students',
            field=models.ManyToManyField(blank=True, related_name='Students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='Teachers',
            field=models.ManyToManyField(blank=True, related_name='Teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='Course',
        ),
        migrations.AddField(
            model_name='lecture',
            name='Course',
            field=models.ManyToManyField(blank=True, related_name='Lecture', to='api.Course'),
        ),
    ]
