# Generated by Django 3.2.3 on 2021-06-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210602_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='Course',
        ),
        migrations.AddField(
            model_name='lecture',
            name='Course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
            preserve_default=False,
        ),
    ]
